title:       BOSSPAN's Homepage 
email:       xiaopanwudlut@sina.com 
author:      BOSSPAN
description: "BOSSPAN's Blog About The Front End"
baseurl:     ""
url:         "http://bosspan.github.io"

duoshuo: bosspan
baidu_analyze: f2650d51e2feb8ab4ec063c520de1ef1
google_analytics:

animated:           true
show_related_posts: true
show_post_footers:  

show_social_icons: true
github_username: bosspan
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

markdown:     kramdown
permalink:    pretty
paginate:     20
sass:
compressed: true