title:       Xpan's Blog
email:       1356101589@qq.com 
author:      xiapanwudlut
description: "The Front End"
baseurl:     ""
url:         "http://bosspan.github.io"

duoshuo: bosspan
baidu_analyze: f2650d51e2feb8ab4ec063c520de1ef1
google_analytics:

animated:           true
show_related_posts: 
show_post_footers:  

show_social_icons: 
github_username: bosspan
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

markdown:     kramdown
permalink:    date
paginate:     20
sass:
compressed: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"